/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Funciones.Funcionalidades;
import Grafo.Grafo;
import Grafo.Vertice;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class AgregarQuitarSucursal extends javax.swing.JFrame {
    
    /**
     * Creates new form AgregarSucursal
     */
    public AgregarQuitarSucursal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volver = new javax.swing.JButton();
        agregar = new javax.swing.JButton();
        quitar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volver.setBackground(new java.awt.Color(204, 204, 255));
        volver.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 18)); // NOI18N
        volver.setForeground(new java.awt.Color(255, 255, 255));
        volver.setText("<  Atrás");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        agregar.setBackground(new java.awt.Color(204, 204, 255));
        agregar.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 24)); // NOI18N
        agregar.setForeground(new java.awt.Color(255, 255, 255));
        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        quitar.setBackground(new java.awt.Color(204, 204, 255));
        quitar.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 24)); // NOI18N
        quitar.setForeground(new java.awt.Color(255, 255, 255));
        quitar.setText("Eliminar");
        quitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarActionPerformed(evt);
            }
        });
        getContentPane().add(quitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Si deseas agregar una sucursal, presiona el boton agregar");
        jPanel1.add(jLabel4);

        jLabel2.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("que se encuentra abajo. ");
        jPanel1.add(jLabel2);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 550, 70));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jLabel3.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Si buscas eliminar una sucursal, presiona el boton eliminar");
        jPanel2.add(jLabel3);

        jLabel5.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("que se encuentra abajo.");
        jPanel2.add(jLabel5);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 550, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/istockphoto-1297178665-612x612.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
       InterfazFunciones.VolverMenu();
    }//GEN-LAST:event_volverActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        Grafo g = InterfazFunciones.getGrafo();
        int T = InterfazFunciones.getT();
        if (g != null){
            Funcionalidades f = new Funcionalidades();
            int i = 0;
            Vertice v = g.getListaParadas().getpFirst();
            while(v!= null){
                for(int j = 0; j < v.getNombre().length; j++){
                    i++;
                }
                v = v.getpNext();
            }
            String[] A = new String[i];
            i = 0;
            v = g.getListaParadas().getpFirst();
            while(v!=null){
                for(int j = 0; j < v.getNombre().length; j++){
                    A[i] = v.getNombre()[j];
                    i++;
                }
                v = v.getpNext();
            }
            String S = (String) JOptionPane.showInputDialog(rootPane, "Seleccione una parada:", "", HEIGHT, null, A, DISPOSE_ON_CLOSE);
            if (S != null){
                v = g.busquedaInicial(S);
                f.seleccionarSucursal(g, v, T);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Seleccione una parada correctamente...");
            }
        }else {
            JOptionPane.showMessageDialog(rootPane, "No ha ingresado ningún grafo...");
        }
    }//GEN-LAST:event_agregarActionPerformed

    private void quitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarActionPerformed
        Grafo g = InterfazFunciones.getGrafo();
        int T = InterfazFunciones.getT();
        if (g != null){
            Funcionalidades f = new Funcionalidades();
            int i = 0;
            Vertice v = g.getListaParadas().getpFirst();
            while(v!= null){
                for(int j = 0; j < v.getNombre().length; j++){
                    i++;
                }
                v = v.getpNext();
            }
            String[] A = new String[i];
            i = 0;
            v = g.getListaParadas().getpFirst();
            while(v!=null){
                for(int j = 0; j < v.getNombre().length; j++){
                    A[i] = v.getNombre()[j];
                    i++;
                }
                v = v.getpNext();
            }
            String S = (String) JOptionPane.showInputDialog(rootPane, "Seleccione una parada con sucursal:", "", HEIGHT, null, A, DISPOSE_ON_CLOSE);
            if (S != null){
                v = g.busquedaInicial(S);
                f.quitarSucursal(g, v, T);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Seleccione una parada correctamente...");
            }
        }else {
            JOptionPane.showMessageDialog(rootPane, "No ha ingresado ningún grafo...");
        }
    }//GEN-LAST:event_quitarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarQuitarSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarQuitarSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarQuitarSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarQuitarSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarQuitarSucursal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton quitar;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
