/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Grafo.BusquedaBFS;
import Grafo.BusquedaDFS;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class Cobertura extends javax.swing.JFrame {

    /**
     * Creates new form ElinimarSucursal
     */
    private int T;
    public Cobertura() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        volver = new javax.swing.JButton();
        vercoberturatotal = new javax.swing.JButton();
        buscarconDFSunpunto = new javax.swing.JButton();
        buscarconBFSunpunto = new javax.swing.JButton();
        buascarDFS = new javax.swing.JButton();
        buscarBFS = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volver.setBackground(new java.awt.Color(204, 204, 255));
        volver.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 18)); // NOI18N
        volver.setForeground(new java.awt.Color(255, 255, 255));
        volver.setText("< Atras  ");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        vercoberturatotal.setBackground(new java.awt.Color(204, 204, 255));
        vercoberturatotal.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 18)); // NOI18N
        vercoberturatotal.setForeground(new java.awt.Color(255, 255, 255));
        vercoberturatotal.setText("Ver Cobertura Total >");
        vercoberturatotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vercoberturatotalActionPerformed(evt);
            }
        });
        getContentPane().add(vercoberturatotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, -1, -1));

        buscarconDFSunpunto.setBackground(new java.awt.Color(255, 204, 102));
        buscarconDFSunpunto.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 24)); // NOI18N
        buscarconDFSunpunto.setText("Búsqueda DFS para un único punto");
        buscarconDFSunpunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarconDFSunpuntoActionPerformed(evt);
            }
        });
        getContentPane().add(buscarconDFSunpunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        buscarconBFSunpunto.setBackground(new java.awt.Color(255, 204, 104));
        buscarconBFSunpunto.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 24)); // NOI18N
        buscarconBFSunpunto.setText("Búsqueda BFS para un único punto");
        buscarconBFSunpunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarconBFSunpuntoActionPerformed(evt);
            }
        });
        getContentPane().add(buscarconBFSunpunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        buascarDFS.setBackground(new java.awt.Color(204, 204, 255));
        buascarDFS.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 24)); // NOI18N
        buascarDFS.setText("Búsqueda DFS");
        buascarDFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buascarDFSActionPerformed(evt);
            }
        });
        getContentPane().add(buascarDFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        buscarBFS.setBackground(new java.awt.Color(204, 204, 255));
        buscarBFS.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 24)); // NOI18N
        buscarBFS.setText("Búsqueda BFS");
        buscarBFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBFSActionPerformed(evt);
            }
        });
        getContentPane().add(buscarBFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/istockphoto-1297178665-612x612.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        InterfazFunciones.VolverMenu();
    }//GEN-LAST:event_volverActionPerformed

    private void buscarconDFSunpuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarconDFSunpuntoActionPerformed
        if (T != 0){
            
        }else {
            
        }
    }//GEN-LAST:event_buscarconDFSunpuntoActionPerformed

    private void buscarconBFSunpuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarconBFSunpuntoActionPerformed
        this.T = InterfazFunciones.getT();
        
    }//GEN-LAST:event_buscarconBFSunpuntoActionPerformed

    private void vercoberturatotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vercoberturatotalActionPerformed
        InterfazFunciones.openCoberturaTotal();
    }//GEN-LAST:event_vercoberturatotalActionPerformed

    private void buscarBFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBFSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarBFSActionPerformed

    private void buascarDFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buascarDFSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buascarDFSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cobertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cobertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cobertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cobertura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cobertura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buascarDFS;
    private javax.swing.JButton buscarBFS;
    private javax.swing.JButton buscarconBFSunpunto;
    private javax.swing.JButton buscarconDFSunpunto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton vercoberturatotal;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
