/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 * Clase Interfaz Menu
 * @author Macorre21
 * @version 1.0
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Constructor de la clase interfaz Menu, no recibe parámetro de entrada
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();
        cargarjson = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        agregarsucursal = new javax.swing.JButton();
        cobertura = new javax.swing.JButton();
        mostrargrafo = new javax.swing.JButton();
        definirrango = new javax.swing.JButton();
        agregarlinea = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        exit.setText("< EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 30));

        cargarjson.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 14)); // NOI18N
        cargarjson.setText("Cargar Json");
        cargarjson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarjsonActionPerformed(evt);
            }
        });
        getContentPane().add(cargarjson, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/7273858.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 90, -1));

        agregarsucursal.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 14)); // NOI18N
        agregarsucursal.setText("Agregar/Quitar Sucursal");
        agregarsucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarsucursalActionPerformed(evt);
            }
        });
        getContentPane().add(agregarsucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        cobertura.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 14)); // NOI18N
        cobertura.setText("Revisar Cobertura");
        cobertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coberturaActionPerformed(evt);
            }
        });
        getContentPane().add(cobertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        mostrargrafo.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 14)); // NOI18N
        mostrargrafo.setText("Mostrar Grafo");
        mostrargrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrargrafoActionPerformed(evt);
            }
        });
        getContentPane().add(mostrargrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, -1));

        definirrango.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 14)); // NOI18N
        definirrango.setText("Definir Rango");
        definirrango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                definirrangoActionPerformed(evt);
            }
        });
        getContentPane().add(definirrango, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        agregarlinea.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 14)); // NOI18N
        agregarlinea.setText("Agregar Línea");
        agregarlinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarlineaActionPerformed(evt);
            }
        });
        getContentPane().add(agregarlinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/images-removebg-preview (1).png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/10964543.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/images-removebg-preview (1).png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, 130));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/camera-radar-logo-6255b4dd-f36f-446e-9ed1-b2b251ac3ae0__1_-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 150, 140));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/vqclwylpTGlxQDbT-removebg-preview (1).png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 100, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/images-removebg-preview (1).png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 130, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/images-removebg-preview (1).png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 230, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/istockphoto-1196819674-612x612-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 120, 100));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/download__1_-removebg-preview.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 120, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/images-removebg-preview (1).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 120, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/images-removebg-preview (1).png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));

        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/istockphoto-1297178665-612x612.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param evt
     * Función para que la clase interfaz CargarJson sea visible al llamar el método
     */
    private void cargarjsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarjsonActionPerformed
        InterfazFunciones.openCargarJson();
    }//GEN-LAST:event_cargarjsonActionPerformed

    /**
     * @param evt
     * Función para que termine la corrida del programa
     */
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param evt
     * Función para que la clase interfaz AgregarSucursal sea visible al llamar el método
     */
    private void agregarsucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarsucursalActionPerformed
        InterfazFunciones.openAgregarQuitarSucursal();
    }//GEN-LAST:event_agregarsucursalActionPerformed

    /**
     * @param evt
     * Función para que la clase interfaz CoberturaTotal sea visible al llamar el método
     */
    private void coberturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coberturaActionPerformed
        InterfazFunciones.openCoberturaTotal();
    }//GEN-LAST:event_coberturaActionPerformed

    /**
     * @param evt
     * Función para que la clase interfaz MostrarGrafo sea visible al llamar el método
     */
    private void mostrargrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrargrafoActionPerformed
       InterfazFunciones.openMostarGraph();
    }//GEN-LAST:event_mostrargrafoActionPerformed

    /**
     * @param evt
     * Función para que la clase interfaz DefinirRango sea visible al llamar el método
     */
    private void definirrangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_definirrangoActionPerformed
        InterfazFunciones.openDefinirRango();
        
    }//GEN-LAST:event_definirrangoActionPerformed

    /**
     * @param evt
     * Función para que la clase interfaz AgregarLinea sea visible al llamar el método
     */
    private void agregarlineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarlineaActionPerformed
        InterfazFunciones.openAgregarLinea();
    }//GEN-LAST:event_agregarlineaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarlinea;
    private javax.swing.JButton agregarsucursal;
    private javax.swing.JButton cargarjson;
    private javax.swing.JButton cobertura;
    private javax.swing.JButton definirrango;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton mostrargrafo;
    // End of variables declaration//GEN-END:variables
}
