/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author User
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cargarjson = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        agregarsucursal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        eliminarsucursal = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        mostrargrafo = new javax.swing.JButton();
        definirrango = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setBackground(new java.awt.Color(204, 204, 255));
        exit.setFont(new java.awt.Font("Algerian", 0, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("< EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/10964543.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 88, 120, 110));

        cargarjson.setBackground(new java.awt.Color(204, 204, 255));
        cargarjson.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 14)); // NOI18N
        cargarjson.setText("Cargar Json");
        cargarjson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarjsonActionPerformed(evt);
            }
        });
        getContentPane().add(cargarjson, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/7273858.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 120, -1));

        agregarsucursal.setBackground(new java.awt.Color(255, 204, 102));
        agregarsucursal.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 14)); // NOI18N
        agregarsucursal.setText("Agregar  Sucursal");
        agregarsucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarsucursalActionPerformed(evt);
            }
        });
        getContentPane().add(agregarsucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/3368864.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 120, -1));

        eliminarsucursal.setBackground(new java.awt.Color(204, 204, 255));
        eliminarsucursal.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 14)); // NOI18N
        eliminarsucursal.setText("Eliminar Sucursal");
        eliminarsucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarsucursalActionPerformed(evt);
            }
        });
        getContentPane().add(eliminarsucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/vqclwylpTGlxQDbT.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 110, -1));

        mostrargrafo.setBackground(new java.awt.Color(255, 204, 102));
        mostrargrafo.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 14)); // NOI18N
        mostrargrafo.setText("Mostrar Grafo");
        mostrargrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrargrafoActionPerformed(evt);
            }
        });
        getContentPane().add(mostrargrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        definirrango.setBackground(new java.awt.Color(255, 204, 102));
        definirrango.setFont(new java.awt.Font("Dutch801 XBd BT", 0, 14)); // NOI18N
        definirrango.setText("Definir Rango");
        definirrango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                definirrangoActionPerformed(evt);
            }
        });
        getContentPane().add(definirrango, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/camera-radar-logo-6255b4dd-f36f-446e-9ed1-b2b251ac3ae0 (1).jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 130, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/istockphoto-1297178665-612x612.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarjsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarjsonActionPerformed
        InterfazFunciones.openCargarJson();
    }//GEN-LAST:event_cargarjsonActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void agregarsucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarsucursalActionPerformed
        InterfazFunciones.openAgregarSucursal();
    }//GEN-LAST:event_agregarsucursalActionPerformed

    private void eliminarsucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarsucursalActionPerformed
        InterfazFunciones.openEliminarSucursal();
    }//GEN-LAST:event_eliminarsucursalActionPerformed

    private void mostrargrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrargrafoActionPerformed
       InterfazFunciones.openMostarGrafo();
    }//GEN-LAST:event_mostrargrafoActionPerformed

    private void definirrangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_definirrangoActionPerformed
        InterfazFunciones.openDefinirRango();
    }//GEN-LAST:event_definirrangoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarsucursal;
    private javax.swing.JButton cargarjson;
    private javax.swing.JButton definirrango;
    private javax.swing.JButton eliminarsucursal;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton mostrargrafo;
    // End of variables declaration//GEN-END:variables
}
